"""Runup V2 도메인 패키지 (Step 02). 불변 DTO·검증·codec만 둔다."""
from runup.domain.base import (
    DomainIssue,
    canonical_json,
    check_fields,
    from_dict,
    stable_key,
    to_dict,
    validate,
)
from runup.domain.collect import CollectionResult
from runup.domain.commands import (
    Actor,
    AllocationApprovalCommand,
    AuthContext,
    CapitalFlowCommand,
    CorporateActionCommand,
    Exposure,
    FillCommand,
    LedgerCommandResult,
    PositionValue,
    ProfileCommand,
    Reservation,
    ReserveExitCommand,
    ReviewCommand,
    SettlementCommand,
    WithdrawalApprovalCommand,
)
from runup.domain.decisions import (
    ConfigSnapshot,
    DecisionSnapshot,
    GateResult,
    ScoreContext,
    ScoreResult,
    SetupContext,
    SetupResult,
    SetupSnapshot,
    TriggerContext,
    TriggerResult,
    TriggerSnapshot,
)
from runup.domain.documents import (
    CatalystRevision,
    EventCandidate,
    Issuer,
    RiskNotice,
    Security,
    SourceDocument,
    UniverseObservation,
)
from runup.domain.enums import (
    CapitalFlowType,
    CollectionStatus,
    CorporateActionType,
    DatePrecision,
    ExitAction,
    FeatureStatus,
    FillSide,
    LedgerCommandStatus,
    SetupState,
    Severity,
    StopAction,
)
from runup.domain.ledger import (
    Allocation,
    Fill,
    LedgerEvent,
    Outbox,
    PositionProjection,
    WithdrawalPeriod,
)
from runup.domain.lifecycle import (
    JobContext,
    OutboxResult,
    ReviewManifest,
    RiskOverlay,
    ScanRun,
    TransportResult,
    UIReadModels,
    UISection,
)
from runup.domain.market import (
    BarContext,
    CorporateAction,
    EvaluationClock,
    FeatureSnapshot,
    FeatureValue,
    MarketContext,
    Pivot,
    PivotSet,
    PriceBar,
    QuoteObservation,
    SourceHealthSnapshot,
)
from runup.domain.trading import (
    AllocationContext,
    AllocationProposal,
    ExitContext,
    ExitDecision,
    LedgerProjection,
    NAVSnapshot,
    SettlementContext,
    SettlementProposal,
    StopContext,
    StopResult,
)

__all__ = [
    "Actor", "Allocation", "AllocationApprovalCommand", "AllocationContext",
    "AllocationProposal", "AuthContext",
    "BarContext", "CapitalFlowCommand", "CapitalFlowType", "CatalystRevision",
    "CollectionResult", "CollectionStatus", "ConfigSnapshot",
    "CorporateAction", "CorporateActionCommand", "CorporateActionType",
    "DatePrecision", "DecisionSnapshot", "DomainIssue", "EvaluationClock",
    "EventCandidate", "ExitAction", "ExitContext", "ExitDecision",
    "Exposure", "FeatureSnapshot", "FeatureStatus", "FeatureValue",
    "Fill", "FillCommand", "FillSide", "GateResult",
    "Issuer", "JobContext", "LedgerCommandResult", "LedgerCommandStatus",
    "LedgerEvent", "LedgerProjection",
    "MarketContext", "NAVSnapshot", "Outbox", "OutboxResult", "Pivot",
    "PivotSet", "PositionProjection", "PositionValue", "PriceBar",
    "ProfileCommand", "QuoteObservation", "Reservation", "ReserveExitCommand",
    "ReviewCommand", "ReviewManifest", "RiskNotice", "RiskOverlay",
    "ScanRun", "ScoreContext", "ScoreResult", "Security",
    "SettlementCommand", "SettlementContext", "SettlementProposal",
    "SetupContext", "SetupResult", "SetupSnapshot", "SetupState",
    "Severity", "SourceDocument", "SourceHealthSnapshot",
    "StopAction", "StopContext", "StopResult",
    "TransportResult", "TriggerContext", "TriggerResult", "TriggerSnapshot",
    "UIReadModels", "UISection", "UniverseObservation",
    "WithdrawalApprovalCommand", "WithdrawalPeriod",
    "canonical_json", "check_fields", "from_dict", "stable_key",
    "to_dict", "validate",
]
